import './globals.css';
import type { Metadata } from 'next';
import { Inter, Anton, Bonheur_Royale, Montserrat } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const anton = Anton({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-anton'
});
const bonheurRoyale = Bonheur_Royale({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-bonheur-royale'
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${anton.variable} ${bonheurRoyale.variable} ${montserrat.variable}`}>{children}</body>
    </html>
  );
}
